### ISSUE TITLE
Location button is not working

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/adaptest#46]
The location button is not working. It just zooms in on the area that was already displayed on the phone screen.

**Comment by GlebRed** [comment]
Was closed in #42

**Comment by tammets** [comment]
The location is displayed correctly, but the geolocation button zooms in on the current view rather than the actual location where the marker is placed.

Chrome 127.0.6533.120

**Comment by GlebRed** [comment]
> The location is displayed correctly, but the geolocation button zooms in on the current view rather than the actual location where the marker is placed.
> 
> Chrome 127.0.6533.120

This is correct behaviour. Find My Location button displays where the user currently is based on the GPS coordinates of their device
