### ISSUE TITLE
Observation form, the options for the field 'Vegetation Coverage'

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/adaptest#49]
In the observation form, the options for the field 'Vegetation Coverage' should be 'very dense to moderate' and 'sparse or absent'.

Est: Vaatlusvormis peaks väljal "Taimestiku katvus" olema variandid "väga tihe kuni keskmine" ja "hõre või puudub"

**Comment by GlebRed** [comment]
Was closed in dd791a047a12e78a9f5492d2647bf524d87a12fb
