### ISSUE TITLE
Using commas in observation form

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/adaptest#50]
If a number with a comma is entered into the observation form, the number is not saved. It also does not display an error message about this. It should either accept both a period and a comma (and convert it to the correct format) or prevent saving if the number is entered in the wrong format.

**Comment by GlebRed** [comment]
Could not reproduce
![Screenshot 2024-07-03 at 11 08 12](https://github.com/user-attachments/assets/40b813fc-91dc-4ea6-b93e-b9085dad028b)
